/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ApiRundownRouteImport } from './routes/api.rundown'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'
import { Route as DatasourcesIndexRouteImport } from './routes/datasources.index'
import { Route as DatasourcesDatasourceIdRouteImport } from './routes/datasources.$datasourceId'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as ApiDatasourceUploadTokenRouteImport } from './routes/api.datasource-upload.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRundownRoute = ApiRundownRouteImport.update({
  id: '/api/rundown',
  path: '/api/rundown',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIndexRoute = DatasourcesIndexRouteImport.update({
  id: '/datasources/',
  path: '/datasources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesDatasourceIdRoute = DatasourcesDatasourceIdRouteImport.update({
  id: '/datasources/$datasourceId',
  path: '/datasources/$datasourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasourceUploadTokenRoute =
  ApiDatasourceUploadTokenRouteImport.update({
    id: '/api/datasource-upload/$token',
    path: '/api/datasource-upload/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/imprint': typeof ImprintRoute
  '/metrics': typeof MetricsRoute
  '/ready': typeof ReadyRoute
  '/api/rundown': typeof ApiRundownRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/datasources/$datasourceId': typeof DatasourcesDatasourceIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/api/datasource-upload/$token': typeof ApiDatasourceUploadTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/imprint': typeof ImprintRoute
  '/metrics': typeof MetricsRoute
  '/ready': typeof ReadyRoute
  '/api/rundown': typeof ApiRundownRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/datasources/$datasourceId': typeof DatasourcesDatasourceIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/datasources': typeof DatasourcesIndexRoute
  '/api/datasource-upload/$token': typeof ApiDatasourceUploadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/imprint': typeof ImprintRoute
  '/metrics': typeof MetricsRoute
  '/ready': typeof ReadyRoute
  '/api/rundown': typeof ApiRundownRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/datasources/$datasourceId': typeof DatasourcesDatasourceIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/api/datasource-upload/$token': typeof ApiDatasourceUploadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/imprint'
    | '/metrics'
    | '/ready'
    | '/api/rundown'
    | '/dashboards/$dashboardId'
    | '/datasources/$datasourceId'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/datasources/'
    | '/api/datasource-upload/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/imprint'
    | '/metrics'
    | '/ready'
    | '/api/rundown'
    | '/dashboards/$dashboardId'
    | '/datasources/$datasourceId'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/datasources'
    | '/api/datasource-upload/$token'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/imprint'
    | '/metrics'
    | '/ready'
    | '/api/rundown'
    | '/dashboards/$dashboardId'
    | '/datasources/$datasourceId'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/datasources/'
    | '/api/datasource-upload/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ImprintRoute: typeof ImprintRoute
  MetricsRoute: typeof MetricsRoute
  ReadyRoute: typeof ReadyRoute
  ApiRundownRoute: typeof ApiRundownRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  DatasourcesDatasourceIdRoute: typeof DatasourcesDatasourceIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  DatasourcesIndexRoute: typeof DatasourcesIndexRoute
  ApiDatasourceUploadTokenRoute: typeof ApiDatasourceUploadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rundown': {
      id: '/api/rundown'
      path: '/api/rundown'
      fullPath: '/api/rundown'
      preLoaderRoute: typeof ApiRundownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/': {
      id: '/datasources/'
      path: '/datasources'
      fullPath: '/datasources/'
      preLoaderRoute: typeof DatasourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$datasourceId': {
      id: '/datasources/$datasourceId'
      path: '/datasources/$datasourceId'
      fullPath: '/datasources/$datasourceId'
      preLoaderRoute: typeof DatasourcesDatasourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasource-upload/$token': {
      id: '/api/datasource-upload/$token'
      path: '/api/datasource-upload/$token'
      fullPath: '/api/datasource-upload/$token'
      preLoaderRoute: typeof ApiDatasourceUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ImprintRoute: ImprintRoute,
  MetricsRoute: MetricsRoute,
  ReadyRoute: ReadyRoute,
  ApiRundownRoute: ApiRundownRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  DatasourcesDatasourceIdRoute: DatasourcesDatasourceIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  DatasourcesIndexRoute: DatasourcesIndexRoute,
  ApiDatasourceUploadTokenRoute: ApiDatasourceUploadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
